### ISSUE TITLE
Editor iframe: Site Editor and Gutenberg Plugin incompatibility 

### ISSUE THREAD

**Issue by antpb** [antpb/three-object-viewer#45]
I noticed in the 15.1 release of Gutenberg that the iframe editor was enabled by default in the single post editor for block based themes and found that it posed some challenges in the context of the WebGL renderer now that it is in an iframe. For whatever reason, it loses half of the context but still seems to get the enqueued scripts to do 3D things using the library in my React app. I'm not yet quite sure how to adjust.

This issue dives deep into the WebGL side of the issue: https://github.com/mrdoob/three.js/issues/25638

Here are a few disgusting options I've considered if this cant be fixed:
1) Defaulting people's sites to a non-iframe version of the editor until the light fades
2) Building the entire editor into the sidebar (I've done a proof of concept of this. It's as gross as it sounds.) Problem comes when you click an innerBlock and it makes the sidebar change.
3) Move all of the 3D editor into a custom post type with a custom react app

WordPress Core Gutenberg issue: 
https://github.com/WordPress/gutenberg/issues/47983

Problem Block: 3D Environment Block - edit state single post editor (does not render, errors forever and ever)
Branch: try-new-react
Setup for 3OV: `nvm use 16 && yarn && yarn run build`
Versions: WordPress 6.2  + Gutenberg latest + Site Editor enabled theme

**Comment by Shelob9** [comment]
@antpb I have been playing with this today.

It is the `ThreeObjectEdit` component we are talking about right?
- https://github.com/antpb/three-object-viewer/blob/try-new-react/blocks/three-object-block/components/ThreeObjectEdit.js
- https://github.com/antpb/three-object-viewer/blob/main/blocks/three-object-block/components/ThreeObjectEdit.js

I am getting different errors, but errors in that branch, with Gutenberg active.

```
### wp-core ###

version: 6.2-RC5


### wp-plugins-active (3) ###

Gutenberg: version: 15.4.0, author: Gutenberg Team, Auto-updates disabled
Three Object Viewer: version: 1.3.1, author: antpb (latest version: 1.3.2), Auto-updates disabled
WordPress Beta Tester: version: 3.3.6, author: WordPress Upgrade/Install Team (latest version: 3.3.7), Auto-updates disabled

```

**Comment by Shelob9** [comment]
@antpb 

## Concerns I have with making this work:

- Are the state updates going from parent to iFrame? Have you confirmed that when you use wp.data.dispatch to update state that both the dispatch and select are in the same frame?  If one is in parent and one is in iFrame, that would explain init not working. I don't think its the problem, but could be. If so, maybe solution is to send state updates via [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)
- When you change state, I'm not convinced its acting on the same ref. 

## Things I would try:

In general, my strategy is to build the simplest version and build up from there. We don't know exactly where this breaks, which is why its hard to solve.

### Blocks Without three.js
- Make a less fancy block that uses canvas, like a block that draws a square and uses wp.data to dispatch changes to it -- width, height, fill color. Load that in the iframed block editor and see if you get same issue.
- If that works, I would figure out a simpel way to use webgl in the block, without threejs. Dont' know if this is practical to do a proof of concept with shading and 3D effects without a dependency like threejs, but if possible, that would tell us if problem is iFrame + webgl or iFrame + threejs.

### Without WordPress, starting without React. 
- Make a simplified version with threejs, without React. Just one HTML page with threejs doing the 3D thing, then make a second html page with a button, that when clicked adds an iFrame to page and its source is other HTML page. 
  - index.html - `<body><iframe src="/3d.htm" />`
  - 3d.html - `<head><script src="3js.js">... <canvas>...` 
- If that works, same experiment, but with the same React library your block is using.

**Comment by antpb** [comment]
This is long solved. yay for Three.js merging my patch :D
